### PR TITLE
require nx >= 2

### PR DESCRIPTION
**Pull request by gboeing**

### CODE REVIEW

**Comment by gboeing** [comment]
@ocefpaf any ideas about this Travis CI error? `Incompatible library version: libgdal.20.dylib requires version 1.4.7 or later, but libkea.1.4.7.dylib provides version 1.4.0
TESTS FAILED: osmnx-0.6-py36_1.tar.bz2`

The tests succeeded for py 2.7 and 3.5 but failed for 3.6. They all succeeded on appveyor and circleci.

**Comment by ocefpaf** [comment]
For some odd reason conda preferred  `gdal 2.1.3` and did not install the accompaning `libgdal` :unamused: 

Let me try to remove that version from the channel to force conda to get the latest one...

**Comment by gboeing** [comment]
@ocefpaf thanks for trying that... looks like the same error is still occurring

**Comment by ocefpaf** [comment]
> @ocefpaf thanks for trying that... looks like the same error is still occurring

I expected that but I need to go build number by build number to find which one would be "OK."

**Comment by gboeing** [comment]
> I expected that but I need to go build number by build number to find which one would be "OK."

That sounds painful. That's for sorting it out! Could you explain briefly what the problem was and what we should look for next time?

**Comment by ocefpaf** [comment]
> That sounds painful.

Indeed.

> Could you explain briefly what the problem was and what we should look for next time?

The problem is hard to debug b/c the conda solver does some things that are not intuitive, like preferring lower build numbers,  or even breaking the channel preference in some cases. 

We need to find out the dependency that is broken and prevent conda from finding them.

**Pull request merged**
