### PR TITLE
version bump to v0.7.4

### PR DESCRIPTION
**Pull request by gboeing**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gboeing did we try to make this `noarch` yet? If you are up to it I can modify this PR for you.
It will safe us CI time by building it only once on CircleCI. (And you get to merge it much faster too :wink:)

**Comment by gboeing** [comment]
@ocefpaf sure, thanks.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please add noarch: python

**Comment by ocefpaf** [comment]
Ready for the merge!

**Comment by gboeing** [comment]
@ocefpaf that's much faster... thanks!

**Pull request merged**
