### PR TITLE
version bump to 1.2.3

### PR DESCRIPTION
**Pull request by gboeing**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gboeing** [comment]
@ocefpaf any idea why CircleCI is failing with this "Could not find a usable config.yml" error?

**Comment by ocefpaf** [comment]
> @ocefpaf any idea why CircleCI is failing with this "Could not find a usable config.yml" error?

Probably a glitch in the hook b/c we no longer use CircleCI for anything. osmnx is noarch so this is ready to be merged. I'll try to delete the CircleCI hook later.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by gboeing** [comment]
> Probably a glitch in the hook b/c we no longer use CircleCI for anything. osmnx is noarch so this is ready to be merged. I'll try to delete the CircleCI hook later.

Ok, thanks. I'll merge now.

**Pull request merged**
