### PR TITLE
version bump to v0.7

### PR DESCRIPTION
**Pull request by gboeing**

### CODE REVIEW

**Comment by gboeing** [comment]
@ocefpaf any idea what's going on with the appveyor tests? It passes circleci and travis-ci, as well as appveyor py35... but appveyor py27 and py36 are failing with error `The batch file cannot be found. Command exited with code 1`

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@gboeing the AppVeyor issue can be fixed by re-rendering. Thanks @isuruf for triggering it~

**Comment by gboeing** [comment]
Thanks. Is there a way to consistently tell when it needs to be re-rendered?

**Comment by ocefpaf** [comment]
> Is there a way to consistently tell when it needs to be re-rendered?

Not really. Problems like that are hard to predict and we do not expect all the maintainers to follow our gitter channel, etc. Rule of thumb? If it fails and a weird way, re-rerender it.

**Comment by gboeing** [comment]
Ok thanks.

**Pull request merged**
