### PR TITLE
version bump to 0.3.1

### PR DESCRIPTION
**Pull request by gboeing**

### CODE REVIEW

**Comment by gboeing** [comment]
@ocefpaf do you have a sense of this circleci failure in the test above? 

```
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```

Looks like a dependency problem with Fiona on Python 3.4. I cannot reproduce this error with py3.4 on my windows box or my linux mint box at home.

**Comment by ocefpaf** [comment]
I probably forgot to re-build something with the latest `icu` and it is forcing its downgrade, and then we are missing the proper version. I am looking into this now and as soon as I fix the dependency I will re-start the CI here.

**Comment by ocefpaf** [comment]
Actually, looking closer, I did not forget any package. The reason for the failures is b/c we dropped support for Python 3.4 and this feedstock is not  re-rendered yet, so it is trying to build for Python 3.4 nonetheless. I will send another PR to re-render and then you can rebase it here. Things should pass after that.

**Comment by ocefpaf** [comment]
I re-rendered in #12. Rebasing this with `master` should fix things now.

**Comment by gboeing** [comment]
@ocefpaf ahhh, thanks much.

**Pull request closed without merging**
